### ISSUE TITLE
FluentMigrator.Tools referencing an old FluentMigrator nuget version

### ISSUE THREAD

**Issue by Ninglin** [cake-contrib/Cake.FluentMigrator#6]
Just noticed that the Tools nuget is referencing version 1.0.1.0 of FluentMigrator NuGet Package. 
This was causing my migrations to be ignored. Is there any relevant reason for this not to be referencing version 1.6.2?

**Comment by Ninglin** [comment]
![fluentmigrator nuspec](https://cloud.githubusercontent.com/assets/1248732/20570742/c3ae4f8a-b19c-11e6-8693-94f9c6815f2a.PNG)
![fluentmigrator tools nuspec](https://cloud.githubusercontent.com/assets/1248732/20570841/12f4e626-b19d-11e6-89f3-5c070be229ec.PNG)

Attaching the nuspec for both of the packages.

**Comment by gep13** [comment]
@Ninglin none that I am aware of.  @FredrikL are you aware of any reason to not update this?

@Ninglin happy to accept a PR to get this updated.
